export const DEFAULT_DEAL_TEMPLATES = [
  {
    name: "TikTok How-To",
    platform: "TikTok",
    contentType: "How-To",
    rateCents: 10000,
    briefSummary: "Face-to-camera how-to under 30s with clear product demo and soft CTA.",
    guidelines: "Show packaging. No medical claims. Hook in first 3 seconds. End with CTA.",
    talkingPoints: "Key benefit\nHow to use\nWho it’s for",
    usageRightsDays: 90,
    deliverablesJson: JSON.stringify([{ title: "TikTok How-To", format: "video" }]),
    checklistJson: JSON.stringify([
      "Confirm talking points",
      "Film primary cut",
      "Self-QC against guidelines",
      "Send draft for review",
    ]),
    sortOrder: 0,
  },
  {
    name: "IG Reel + stills",
    platform: "Instagram",
    contentType: "Product Review",
    rateCents: 12000,
    briefSummary: "Vertical Reel review plus 3–5 UGC product stills.",
    guidelines: "Natural light. Soft glam. Disclose gifted/paid as required.",
    talkingPoints: "First impression\nTexture/feel\nRoutine fit",
    usageRightsDays: 90,
    deliverablesJson: JSON.stringify([
      { title: "IG Reel", format: "video" },
      { title: "UGC stills set", format: "image" },
    ]),
    checklistJson: JSON.stringify([
      "Confirm brief",
      "Film Reel",
      "Shoot stills",
      "Deliver draft pack",
    ]),
    sortOrder: 1,
  },
  {
    name: "YouTube Shorts unboxing",
    platform: "YouTube Shorts",
    contentType: "Unboxing",
    rateCents: 8000,
    briefSummary: "Unboxing + first impressions cut for Shorts.",
    guidelines: "Keep under 60s. Show seal/label. Honest reaction.",
    talkingPoints: "Packaging\nFirst use\nWould repurchase?",
    usageRightsDays: 60,
    deliverablesJson: JSON.stringify([{ title: "Shorts unboxing", format: "video" }]),
    checklistJson: JSON.stringify(["Unbox on camera", "Edit Short", "Add captions", "Deliver"]),
    sortOrder: 2,
  },
  {
    name: "UGC images only",
    platform: "Multi",
    contentType: "UGC Images",
    rateCents: 3000,
    briefSummary: "Product-focused stills pack for ads/PDP.",
    guidelines: "Clean background options. Hands + hero product. No heavy filters.",
    talkingPoints: "",
    usageRightsDays: 120,
    deliverablesJson: JSON.stringify([{ title: "Stills pack (5+)", format: "image" }]),
    checklistJson: JSON.stringify(["Shot list confirmed", "Shoot set", "Select finals", "Deliver ZIP"]),
    sortOrder: 3,
  },
];
