export const FALLBACK_PORTFOLIO = [
  {
    id: "fallback-1",
    title: "Silk press how-to",
    category: "Hair",
    description: "Step-by-step heat protect + finish routine",
    platform: "TikTok",
    featured: true,
    sortOrder: 0,
  },
  {
    id: "fallback-2",
    title: "Serum unboxing",
    category: "Beauty",
    description: "First impressions with soft natural light",
    platform: "Instagram",
    featured: true,
    sortOrder: 1,
  },
  {
    id: "fallback-3",
    title: "Morning wellness stack",
    category: "Wellness",
    description: "Calm lifestyle review for supplements",
    platform: "YouTube Shorts",
    featured: true,
    sortOrder: 2,
  },
  {
    id: "fallback-4",
    title: "Outfit texture reel",
    category: "Fashion",
    description: "Movement-led apparel storytelling",
    platform: "Instagram",
    featured: false,
    sortOrder: 3,
  },
  {
    id: "fallback-5",
    title: "Amazon product demo",
    category: "Demo",
    description: "Clean surface demo built for conversion",
    platform: "Amazon",
    featured: true,
    sortOrder: 4,
  },
  {
    id: "fallback-6",
    title: "Selfie product stills",
    category: "Images",
    description: "On-camera product detail set",
    platform: "UGC Images",
    featured: false,
    sortOrder: 5,
  },
];
